### ISSUE TITLE
部署后404

### ISSUE THREAD

**Issue by RemotePinee** [Panyoujies/zlianpay-faka#4]
<img src="https://s2.loli.net/2022/08/16/Ro7fVmh41u659YT.png" width="100%"></img>

**Comment by Panyoujies** [comment]
我看看

**Comment by Panyoujies** [comment]
https://github.com/Panyoujies/zlianpay-faka/releases/tag/2.0.2
已更新

**Comment by RemotePinee** [comment]
> https://github.com/Panyoujies/zlianpay-faka/releases/tag/2.0.2 已更新

现在部署好报500错误，会是MySQL版本原因吗？我的是5.6，之前的版本我用5.6也部署成功了，以下是项目日志：
`at com.sun.proxy.$Proxy151.query(Unknown Source) ~[na:na]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151) ~[mybatis-3.5.10.jar:3.5.10]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145) ~[mybatis-3.5.10.jar:3.5.10]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.10.jar:3.5.10]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76) ~[mybatis-3.5.10.jar:3.5.10]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0-internal]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0-internal]
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427) ~[mybatis-spring-2.0.7.jar:2.0.7]
... 106 common frames omitted`

**Comment by RemotePinee** [comment]
已解决
